# host := "172.31.164.78:6699"
host := "localhost:6699"

default:
    @just -l

# Makes a GET request to the server to look up name
get name:
    curl -s http://{{host}}/v2/get/{{name}} | jq

# Makes a GET request to the server to match name
find name:
    curl -s http://{{host}}/v2/find/{{name}} | jq

# Makes a post request to the server
post path:
    @printf '{"data":"' > req.json
    @base64 -w 0 "{{path}}" >> req.json
    @echo '"}' >> req.json

    @curl http://{{host}}/v2/search -s \
        --header "Content-Type: application/json" \
        --request POST \
        --data @req.json | jq

    @rm req.json
